### ISSUE TITLE
mouse server disconnects after 24hrs of inactivity

### ISSUE THREAD

**Issue by ssfrr** [ssfrr/advenshare#4]
The mouse server seems to disconnect exactly 24 hours after the last message. We should configure it to reconnect automatically if the connection drops.

**Comment by bmayton** [comment]
The disconnection is almost certainly HAProxy timing out the connection due to inactivity (a reasonable thing to do after 24 hours).  I'll change the script so that it reconnects.

**Comment by bmayton** [comment]
Reconnection should now be implemented as of 8e01a682db06bd573fbd1d056471323b87885f77.
